version: '3'

services:

# SOC

## OpenSearch
#     build: ./components/opensearch
#     build: ./components/opensearch
#    build: ./components/opensearch_dashboards

  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-node1
    restart: always
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and later
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/config/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/config/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/config/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/config/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/bin/adminpassword.sh:/usr/share/opensearch/bin/adminpassword.sh
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    command: >
      bash -c "
      /usr/share/opensearch/opensearch-docker-entrypoint.sh"
#      sleep 30 &&
#      /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/opensearch/config/opensearch-security -icl -nhnv -cacert /usr/share/opensearch/config/root-ca.pem -cert /usr/share/opensearch/config/kirk.pem -key /usr/share/opensearch/config/kirk-key.pem -h localhost -p 9200 &&
#      wait"
#    networks:
#      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-node2:
    image: opensearchproject/opensearch:latest # This should be the same image used for opensearch-node1 to avoid issues
    container_name: opensearch-node2
    restart: always
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/config/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/config/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/config/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/config/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ${USER_HOME}/pocketsoc-ng/components/opensearch/bin/adminpassword.sh:/usr/share/opensearch/bin/adminpassword.sh
    command: >
      bash -c "
      /usr/share/opensearch/opensearch-docker-entrypoint.sh"
#      sleep 30 &&
#      /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/opensearch/config/opensearch-security -icl -nhnv -cacert /usr/share/opensearch/config/root-ca.pem -cert /usr/share/opensearch/config/kirk.pem -key /usr/share/opensearch/config/kirk-key.pem -h localhost -p 9200 &&
#      wait"
#    networks:
#      - mirror

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    restart: always
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    volumes:
    - ${USER_HOME}/pocketsoc-ng/components/opensearch_dashboards/config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    - certificates:/usr/share/opensearch-dashboards/config/certs
#    - ${USER_HOME}/root-ca.pem:/usr/share/opensearch-dashboards/config/certs/root-ca.pem
    command: >
      /bin/sh -c "
      sleep 30 &&
      /usr/share/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh
      "
#    networks:
#      - mirror


## Zeek

  zeek:
    build: ./components/zeek/
    container_name: zeek
    restart: always
    volumes:
      - zeek_data:/opt/pocketsoc-ng/data
    environment:
        ZEEKHOST: ${HOST_HOSTNAME}
    #privileged: true
    cap_add:
      - NET_ADMIN
#    networks:
#      - mirror

## "Internal"

## Client

  client:
    build: ./components/client/
    container_name: client
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - certificates:/certs
      - client_data:/opt/pocketsoc-ng/data
#    networks:
#      - internal
#      - mirror

# "External"

## Webserver

  webserver:
    build: ./components/webserver/
    container_name: webserver
    restart: always

    cap_add:
      - NET_ADMIN
    volumes:
      - webserver_data:/usr/local/apache2/htdocs/
      - certificates:/certs
#    networks:
#      - internal

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-dashboards:
  misp_mysql_data:
  misp_data:
  router_data:
  webserver_data:
  client_data:
  sshserver_data:
  zeek_data:
  docs_data:
  certificates:
    external: true

