version: '3'

services:

# SOC


## Zeek

  zeek:
    build: ./components/zeek/
    container_name: zeek
    restart: always
    volumes:
      - zeek_data:/opt/pocketsoc-ng/data
    environment:
        ZEEKHOST: ${HOST_HOSTNAME}
    #privileged: true
    cap_add:
      - NET_ADMIN
#    networks:
#      - mirror

## "Internal"

## Client

  client:
    build: ./components/client/
    container_name: client
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - certificates:/certs
      - client_data:/opt/pocketsoc-ng/data
#    networks:
#      - internal
#      - mirror

# "External"

## Webserver

  webserver:
    build: ./components/webserver/
    container_name: webserver
    restart: always

    cap_add:
      - NET_ADMIN
    volumes:
      - webserver_data:/usr/local/apache2/htdocs/
      - certificates:/certs
#    networks:
#      - internal

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-dashboards:
  misp_mysql_data:
  misp_data:
  router_data:
  webserver_data:
  client_data:
  sshserver_data:
  zeek_data:
  docs_data:
  certificates:
    external: true

